from PyQt5 import QtCore, QtGui, QtWidgets
from Game_Logic import Ui_Form
import sqlite3 as sql
conn = sql.connect("Name.db")
cur = conn.cursor()
cur.execute("DELETE FROM Player_Name;")
conn.commit()
class Ui_Form_(object):
    def Function(self):
        # """
        # The function takes input from two line edits, inserts the values into a database table, and then
        # hides the current form and shows a new form.
        # """
       p1 = self.lineEdit_1.text()
       player1 = p1.strip()
       p2 = self.lineEdit_2.text()
       player2 = p2.strip()
       if player1 != "" and player2 != "":
            insert_query = """INSERT INTO Player_Name(Player_1,Player_2)VALUES(?,?);"""
            cur.execute(insert_query, (player1,player2))
            conn.commit()
            self.window = QtWidgets.QWidget()
            self.ui = Ui_Form()
            self.ui.setupUi(self.window)
            Form.hide()
            self.window.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 564)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setText("")
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.verticalLayout.addWidget(self.lineEdit_1)
        self.label_1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(20)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.pushButton_1.clicked.connect(self.Function)

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.lineEdit_1.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tic_Tac_Toe"))
        self.lineEdit_1.setPlaceholderText(_translate("Form", "Enter Player 1 Name"))
        self.label_1.setText(_translate("Form", "Vs"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Enter Player 2 Name"))
        self.pushButton_1.setText(_translate("Form", "OK"))
        self.pushButton_2.setText(_translate("Form", "Reset"))
        self.label.setText(_translate("Form", "Rules :"))
        self.label_2.setText(_translate("Form", "1. Player 1 will start the game and use \'X\' marks."))
        self.label_3.setText(_translate("Form", "2. Player 2 follows with \'O\' marks. "))
        self.label_4.setText(_translate("Form", "3.  Player 1 makes the first move with an \'X\' mark in an empty cell of their choice."))
        self.label_5.setText(_translate("Form", "4. Players then alternate turns, placing their respective marks on the board."))
        self.label_6.setText(_translate("Form", "5. The game is won if a player succeeds in placing three of their marks (\'X\' or \'O\') in a horizontal, vertical, or diagonal row. "))
        self.label_7.setText(_translate("Form", "6. The game ends immediately once a player achieves this."))
        self.label_8.setText(_translate("Form", "7.  If all the cells are filled and neither player has achieved a winning combination, the game ends in a draw."))
        self.label_9.setText(_translate("Form", "8. After the game ends (either by a win or a draw), players may choose to play another round or reset the game."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
